version: "3.9"
services:
  postgres:
    image: postgres:13-alpine 
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  restapp:
    image: 'restapp:latest'
    build:
      context: .
    container_name: restapp
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres?&useSSL=false&amp;serverTimezone=UTC
    ports:
      - "8091:8091"